# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d30a301d36f6af41456baeb1966ed2c"
name = "fruit-app"
handle = "fruit-app-3"
application_url = "https://dare-ion-alt-crimes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tuanna2704-store1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://dare-ion-alt-crimes.trycloudflare.com/auth/callback",
  "https://dare-ion-alt-crimes.trycloudflare.com/auth/shopify/callback",
  "https://dare-ion-alt-crimes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
